title: ANote
description: A Note for Learning.
author: Luojiecn
avatar: /logo.png
email: boiior@163.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: Luojiecn
  card: summary
logo: logo.png
social:
  name: Luojiecn
  links:
    - https://twitter.com/
    - https://www.facebook.com/
    - https://github.com/
#google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
